// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-<%= type %>',
  name: '<%= componentName %>',
  content: '<%= content %>',
}

export default getIconByMeta(meta)
